import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from '~/components/ui/toaster';
import { GoogleAnalytics } from '@next/third-parties/google'


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en" className={`${GeistSans.variable}`}>
      <body>{children}</body>
      <GoogleAnalytics gaId="G-Y5GJKN3V0L" />

      <Toaster />
    </html>
    </>
    
  );
}

